In [1]:
import pandas as pd

In [2]:
df = pd.read_parquet("dagma/df_dagma_unificado_master.parquet")

In [4]:
df.head()

,nombre_est,tipo_gas,concentracion,fecha,fuente,estacion_id,latitud,longitud,altitud,municipio,...,era5_u_component_of_wind_10m,era5_v_component_of_wind_10m,era5_boundary_layer_height,era5_relative_humidity_850hPa,era5_surface_pressure,era5_total_precipitation,modis_Optical_Depth_047,modis_Optical_Depth_055,modis_Column_WV,modis_AOD_QA
0,base aerea,o3,7.258768,2021-01-01 00:00:00,cristian,8285,3.457128,-76.502303,956.0,santiago de cali,...,0.635958,0.042928,66.486206,92.139053,85114.851562,0.000229,NaN,NaN,2.6160,1283.0
1,canaveralejo,so2,2.147011,2021-01-01 00:00:00,cristian,30109,3.411100,-76.544400,975.0,santiago de cali,...,0.635958,0.042928,66.486206,92.139053,85114.851562,0.000229,NaN,NaN,3.4740,1283.0
2,compartir,o3,1.020151,2021-01-01 00:00:00,cristian,30110,3.425800,-76.474100,960.0,santiago de cali,...,-0.595803,-0.791871,76.722900,88.768860,89287.984375,0.000057,NaN,NaN,3.4925,1283.0
3,estacion yumbo,no2,6.170000,2021-01-01 00:00:00,cvc,8777,3.579075,-76.489558,950.0,yumbo,...,-0.035294,-1.490951,147.432007,91.495483,85763.992188,0.000020,NaN,NaN,3.6490,1283.0
4,base aerea,o3,13.163875,2021-01-01 01:00:00,cristian,8285,3.457128,-76.502303,956.0,santiago de cali,...,0.573469,-0.515015,83.873779,92.139053,85164.945312,0.000631,NaN,NaN,2.6160,1283.0

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 300025 entries, 0 to 300024
Data columns (total 22 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   nombre_est                     300025 non-null  str
 1   tipo_gas                       300025 non-null  str
 2   concentracion                  300025 non-null  float64
 3   fecha                          300025 non-null  datetime64[us]
 4   fuente                         300025 non-null  str
 5   estacion_id                    300025 non-null  int64
 6   latitud                        300025 non-null  float64
 7   longitud                       300025 non-null  float64
 8   altitud                        300025 non-null  float64
 9   municipio                      300025 non-null  str
 10  era5_temperature_2m            300025 non-null  float32
 11  era5_dewpoint_temperature_2m   300025 non-null  float32
 12  era5_u_component_of_wind_10m   300025 non-null  float32
 13  era5_v_component_of_wind_10m   300025 non-null  float32
 14  era5_boundary_layer_height     300025 non-null  float32
 15  era5_relative_humidity_850hPa  300025 non-null  float32
 16  era5_surface_pressure          300025 non-null  float32
 17  era5_total_precipitation       299805 non-null  float32
 18  modis_Optical_Depth_047        44120 non-null   float32
 19  modis_Optical_Depth_055        44120 non-null   float32
 20  modis_Column_WV                283270 non-null  float32
 21  modis_AOD_QA                   300025 non-null  float32
dtypes: datetime64[us](1), float32(12), float64(4), int64(1), str(4)
memory usage: 46.3 MB

In [6]:
print(f"Desde: {df['fecha'].min()} hasta {df['fecha'].max()}")

Desde: 2021-01-01 00:00:00 hasta 2024-12-31 23:00:00

In [7]:
print("\nValores únicos de Latitud:")
print(df['latitud'].unique())

print("\nValores únicos de Longitud:")
print(df['longitud'].unique())

print("\nValores únicos de Altitud:")
print(df['altitud'].unique())

Valores únicos de Latitud:
[3.457128 3.4111   3.4258   3.579075 3.4533   3.3214   3.3768   3.4792
 3.4525   3.42826  3.377911 3.457317 3.455514 3.416366 3.304517 3.488218]

Valores únicos de Longitud:
[-76.502303 -76.5444   -76.4741   -76.489558 -76.5311   -76.5333
 -76.5336   -76.5072   -76.5222   -76.466584 -76.533811 -76.506539
 -76.530978 -76.549613 -76.531252 -76.518058]

Valores únicos de Altitud:
[ 956.  975.  960.  950.  962. 1100.  980.  952.  965.  985.  968.  994.
  978.  959.]

In [8]:
df.describe()

,concentracion,fecha,estacion_id,latitud,longitud,altitud,era5_temperature_2m,era5_dewpoint_temperature_2m,era5_u_component_of_wind_10m,era5_v_component_of_wind_10m,era5_boundary_layer_height,era5_relative_humidity_850hPa,era5_surface_pressure,era5_total_precipitation,modis_Optical_Depth_047,modis_Optical_Depth_055,modis_Column_WV,modis_AOD_QA
count,300025.000000,300025,300025.000000,300025.000000,300025.000000,300025.000000,300025.000000,300025.000000,300025.000000,300025.000000,300025.000000,300025.000000,300025.000000,2.998050e+05,44120.000000,44120.000000,283270.000000,300025.000000
mean,13.624164,2023-02-13 13:58:46.326140,16628.675380,3.439250,-76.514929,974.619152,293.556732,291.454041,0.527501,-0.221560,242.991196,91.017899,85682.179688,5.580563e-04,0.330657,0.239645,1.909128,907.582397
min,0.000000,2021-01-01 00:00:00,8285.000000,3.304517,-76.549613,950.000000,287.376801,287.093903,-2.491610,-3.053802,10.605022,51.908485,76745.593750,-3.725290e-09,0.000000,0.000000,0.089000,0.000000
25%,2.565940,2022-04-13 03:00:00,8291.000000,3.411100,-76.533300,956.000000,291.571106,290.600098,-0.011468,-0.707451,62.952148,88.843819,85145.742188,3.926270e-05,0.222000,0.160000,0.961000,1.000000
50%,6.984112,2023-03-06 07:00:00,8986.000000,3.452500,-76.522200,962.000000,293.179047,291.367523,0.562643,-0.195496,123.988304,91.757530,85267.773438,1.989612e-04,0.336000,0.243000,1.896000,1283.000000
75%,15.851581,2024-01-07 17:00:00,30109.000000,3.457128,-76.502303,975.000000,295.324707,292.209747,1.059082,0.321882,389.135986,94.036026,85425.453125,6.102743e-04,0.443000,0.322000,2.755000,1283.000000
max,86.771710,2024-12-31 23:00:00,30111.000000,3.579075,-76.466584,1100.000000,304.649048,298.591614,4.614506,2.419888,3116.171143,100.928642,89919.820312,2.289673e-02,0.910000,0.669000,5.232000,2818.000000
std,17.657863,NaN,10447.892185,0.062542,0.021073,40.265514,2.471130,1.224281,0.723998,0.661147,241.514816,4.598583,1241.794434,1.005938e-03,0.160932,0.117694,1.075521,575.202209